import { Buffer } from 'buffer';
import { CipherGCMTypes, createCipheriv, createDecipheriv, randomBytes } from 'crypto';
import { promisify } from 'util';

import { isNonEmptyString } from '@guarani/primitives';

import { InvalidJoseHeaderError } from '../../../../errors/invalid-jose-header.error';
import { InvalidJsonWebEncryptionError } from '../../../../errors/invalid-jsonwebencryption.error';
import { InvalidJsonWebKeyError } from '../../../../errors/invalid-jsonwebkey.error';
import { JsonWebEncryptionHeader } from '../../../../jwe/jsonwebencryption-header';
import { OctetSequenceJsonWebKey } from '../../../jwk/oct/octet-sequence.jsonwebkey';
import { JsonWebEncryptionKeyManagementBackend } from '../jsonwebencryption-key-management.backend';
import { KeyManagementAlgorithm } from '../key-management-algorithm.type';
import { AESGCMKWJsonWebEncryptionKeyManagementHeaderParameters } from './aesgcmkw-jsonwebencryption-key-management-header.parameters';

const randomBytesAsync = promisify(randomBytes);

/**
 * Implementation of the AES GCM Key Wrap JSON Web Encryption Key Management Backend.
 *
 * @see {@link https://www.rfc-editor.org/rfc/rfc7518.html#section-4.7|RFC 7518 Key Encryption with AES GCM}
 */
export class AESGCMKWJsonWebEncryptionKeyManagementBackend extends JsonWebEncryptionKeyManagementBackend {
  /**
   * Size of the Wrap Key in bytes.
   */
  private readonly keySize: number;

  /**
   * Cipher Algorithm.
   */
  private readonly cipher: CipherGCMTypes;

  /**
   * Size of the Initialization Vector in bytes.
   */
  private readonly ivSize: number = 12;

  /**
   * Size of the Authentication Tag in bytes.
   */
  private readonly authTagLength: number = 16;

  /**
   * Additional Authenticated Data.
   */
  private readonly aad: Buffer = Buffer.alloc(0);

  /**
   * Instantiates a new AES GCM Key Wrap JSON Web Encryption Key Management Backend.
   *
   * @param algorithm JSON Web Encryption Algorithm.
   */
  public constructor(algorithm: Extract<KeyManagementAlgorithm, 'A128GCMKW' | 'A192GCMKW' | 'A256GCMKW'>) {
    super(algorithm);

    const bitSize = Number.parseInt(algorithm.substring(1, 4));

    this.keySize = bitSize >> 3;
    this.cipher = `aes-${bitSize}-gcm` as CipherGCMTypes;
  }

  /**
   * Wraps the provided Content Encryption Key.
   *
   * If additional header parameters are generated by the backend,
   * it will be automatically added to the header by the method.
   *
   * @param cek Content Encryption Key.
   * @param jwk JSON Web Key used to wrap the Content Encryption Key.
   * @param header JSON Web Encryption Header.
   * @throws {InvalidJsonWebKeyError} The provided JSON Web Key cannot be used by the JSON Web Encryption Key Management Algorithm.
   * @throws {InvalidJoseHeaderError} The provided JSON Web Encryption Header Parameters are invalid.
   * @returns Encrypted Key.
   */
  public async wrap(cek: Buffer, jwk: OctetSequenceJsonWebKey, header: JsonWebEncryptionHeader): Promise<Buffer> {
    this.validateJsonWebKey(jwk);

    const iv = await randomBytesAsync(this.ivSize);
    const cipher = createCipheriv(this.cipher, jwk.cryptoKey, iv, { authTagLength: this.authTagLength });

    cipher.setAAD(this.aad);

    const ek = Buffer.concat([cipher.update(cek), cipher.final()]);
    const tag = cipher.getAuthTag();

    const headerParameters: Partial<AESGCMKWJsonWebEncryptionKeyManagementHeaderParameters> = {
      iv: iv.toString('base64url'),
      tag: tag.toString('base64url'),
    };

    Object.assign(header.parameters, headerParameters);

    return ek;
  }

  /**
   * Unwraps the provided Encrypted Key.
   *
   * @param ek Encrypted Key.
   * @param jwk JSON Web Key used to unwrap the Encrypted Key.
   * @param header JSON Web Encryption Header.
   * @throws {InvalidJsonWebKeyError} The provided JSON Web Key cannot be used by the JSON Web Encryption Key Management Algorithm.
   * @throws {InvalidJoseHeaderError} The provided JSON Web Encryption Header Parameters are invalid.
   * @throws {InvalidJsonWebEncryptionError} Failed to unwrap the provided Encrypted Key.
   * @returns Content Encryption Key.
   */
  public async unwrap(
    ek: Buffer,
    jwk: OctetSequenceJsonWebKey,
    header: JsonWebEncryptionHeader<AESGCMKWJsonWebEncryptionKeyManagementHeaderParameters>,
  ): Promise<Buffer> {
    this.validateJsonWebKey(jwk);
    this.validateJoseHeaderParameters(header.parameters);

    const iv = Buffer.from(header.parameters.iv, 'base64url');
    const tag = Buffer.from(header.parameters.tag, 'base64url');

    const decipher = createDecipheriv(this.cipher, jwk.cryptoKey, iv, { authTagLength: this.authTagLength });

    decipher.setAAD(this.aad);
    decipher.setAuthTag(tag);

    try {
      return Buffer.concat([decipher.update(ek), decipher.final()]);
    } catch (error: unknown) {
      throw new InvalidJsonWebEncryptionError('The provided JSON Web Encryption is invalid.', { cause: error });
    }
  }

  /**
   * Generates a new Content Encryption Key.
   *
   * @param jwk JSON Web Key used to wrap the Content Encryption Key.
   * @param header JSON Web Encryption Header.
   * @throws {InvalidJsonWebKeyError} The provided JSON Web Key cannot be used by the JSON Web Encryption Key Management Algorithm.
   * @throws {InvalidJoseHeaderError} The provided JSON Web Encryption Header Parameters are invalid.
   * @throws {InvalidJsonWebEncryptionError} Failed to generate a Content Encryption Key.
   * @returns Generated Content Encryption Key.
   */
  public async generateContentEncryptionKey(
    jwk: OctetSequenceJsonWebKey,
    header: JsonWebEncryptionHeader,
  ): Promise<Buffer> {
    this.validateJsonWebKey(jwk);
    return await randomBytesAsync(header.contentEncryptionBackend.cekSize);
  }

  /**
   * Checks if the provided JSON Web Key can be used.
   *
   * @param jwk JSON Web Key to be checked.
   * @throws {InvalidJsonWebKeyError} The provided JSON Web Key cannot be used by the JSON Web Encryption Key Management Algorithm.
   */
  protected override validateJsonWebKey(jwk: OctetSequenceJsonWebKey): void {
    super.validateJsonWebKey(jwk);

    if (jwk.parameters.kty !== 'oct') {
      throw new InvalidJsonWebKeyError('The JSON Web Encryption Algorithm only accepts "oct" JSON Web Keys.');
    }

    if (Buffer.byteLength(jwk.parameters.k, 'base64url') !== this.keySize) {
      throw new InvalidJsonWebKeyError(`The JSON Web Key Parameter "k" must be ${this.keySize} bytes.`);
    }
  }

  /**
   * Validates the provided JOSE Header Parameters.
   *
   * @param parameters JOSE Header Parameters.
   * @throws {InvalidJoseHeaderError} The provided JOSE Header Parameters are invalid.
   */
  private validateJoseHeaderParameters(parameters: AESGCMKWJsonWebEncryptionKeyManagementHeaderParameters): void {
    if (!isNonEmptyString(parameters.iv) || Buffer.byteLength(parameters.iv, 'base64url') !== this.ivSize) {
      throw new InvalidJoseHeaderError('Invalid JOSE Header Parameter "iv".');
    }

    if (!isNonEmptyString(parameters.tag) || Buffer.byteLength(parameters.tag, 'base64url') !== this.authTagLength) {
      throw new InvalidJoseHeaderError('Invalid JOSE Header Parameter "tag".');
    }
  }
}
