import { Buffer } from 'buffer';
import { createHash, diffieHellman, randomBytes } from 'crypto';
import { promisify } from 'util';

import { isNonEmptyString } from '@guarani/primitives';

import { InvalidJoseHeaderError } from '../../../../errors/invalid-jose-header.error';
import { InvalidJsonWebKeyError } from '../../../../errors/invalid-jsonwebkey.error';
import { JsonWebEncryptionHeader } from '../../../../jwe/jsonwebencryption-header';
import { create } from '../../../../jwk/create';
import { JsonWebKey } from '../../../../jwk/jsonwebkey';
import { EllipticCurveJsonWebKey } from '../../../jwk/ec/elliptic-curve.jsonwebkey';
import { EllipticCurve } from '../../../jwk/ec/elliptic-curve.type';
import { OctetSequenceJsonWebKey } from '../../../jwk/oct/octet-sequence.jsonwebkey';
import { MontgomeryCurve } from '../../../jwk/okp/montgomery-curve.type';
import { OctetKeyPairJsonWebKey } from '../../../jwk/okp/octet-key-pair.jsonwebkey';
import { AESKWJsonWebEncryptionKeyManagementBackend } from '../aeskw/aeskw-jsonwebencryption-key-management.backend';
import { JsonWebEncryptionKeyManagementBackend } from '../jsonwebencryption-key-management.backend';
import { KeyManagementAlgorithm } from '../key-management-algorithm.type';
import { ECDHESJsonWebEncryptionKeyManagementHeaderParameters } from './ecdhes-jsonwebencryption-key-management-header.parameters';

const randomBytesAsync = promisify(randomBytes);

/**
 * Implementation of the ECDH-ES JSON Web Encryption Key Management Backend.
 *
 * @see {@link https://www.rfc-editor.org/rfc/rfc7518.html#section-4.6|RFC 7518 Key Agreement with Elliptic Curve Diffie-Hellman Ephemeral Static}
 */
export class ECDHESJsonWebEncryptionKeyManagementBackend extends JsonWebEncryptionKeyManagementBackend {
  /**
   * Supported ECDH-ES Curves.
   *
   * @see {@link https://www.rfc-editor.org/rfc/rfc7518.html#section-6.2.1.1|RFC 7518 "crv" (Curve) Parameter}
   * @see {@link https://www.rfc-editor.org/rfc/rfc8037.html#section-3.2|RFC 8037 ECDH-ES}
   * @see {@link https://www.rfc-editor.org/rfc/rfc8812.html#section-3.1|RFC 8812 JOSE secp256k1 Curve Key Representation}
   */
  static readonly #curves: (EllipticCurve | MontgomeryCurve)[] = [
    'P-256',
    'P-384',
    'P-521',
    'X25519',
    'X448',
    'secp256k1',
  ];

  /**
   * AES Key Wrap JSON Web Encryption Key Management Backend.
   */
  private readonly aesKeyWrapBackend?: AESKWJsonWebEncryptionKeyManagementBackend;

  /**
   * Instantiates a new ECDH-ES JSON Web Encryption Key Management Backend.
   *
   * @param algorithm JSON Web Encryption Key Management Algorithm.
   */
  public constructor(
    algorithm: Extract<KeyManagementAlgorithm, 'ECDH-ES' | 'ECDH-ES+A128KW' | 'ECDH-ES+A192KW' | 'ECDH-ES+A256KW'>,
  ) {
    super(algorithm);

    if (algorithm !== 'ECDH-ES') {
      this.aesKeyWrapBackend = new AESKWJsonWebEncryptionKeyManagementBackend(
        algorithm.substring(8) as Extract<KeyManagementAlgorithm, 'A128KW' | 'A192KW' | 'A256KW'>,
      );
    }
  }

  /**
   * Wraps the provided Content Encryption Key.
   *
   * If additional header parameters are generated by the backend,
   * it will be automatically added to the header by the method.
   *
   * @param contentEncryptionKey Content Encryption Key.
   * @param jsonWebKey JSON Web Key used to wrap the Content Encryption Key.
   * @param header JSON Web Encryption Header.
   * @throws {InvalidJsonWebKeyError} The provided JSON Web Key cannot be used by the JSON Web Encryption Key Management Algorithm.
   * @throws {InvalidJoseHeaderError} The provided JSON Web Encryption Header Parameters are invalid.
   * @returns Encrypted Key.
   */
  public async wrap(
    contentEncryptionKey: Buffer,
    jsonWebKey: EllipticCurveJsonWebKey | OctetKeyPairJsonWebKey,
    header: JsonWebEncryptionHeader<ECDHESJsonWebEncryptionKeyManagementHeaderParameters>,
  ): Promise<Buffer> {
    this.validateJsonWebKey(jsonWebKey);
    await this.validateJoseHeaderParameters(header.parameters);

    switch (this.algorithm) {
      case 'ECDH-ES':
        return Buffer.alloc(0);

      default: {
        const sharedSecret = await this.deriveKey(jsonWebKey, header);

        const aesKeyWrapJsonWebKey = (await create({
          kty: 'oct',
          k: sharedSecret.toString('base64url'),
        })) as OctetSequenceJsonWebKey;

        return await this.aesKeyWrapBackend!.wrap(contentEncryptionKey, aesKeyWrapJsonWebKey, header);
      }
    }
  }

  /**
   * Unwraps the provided Encrypted Key.
   *
   * @param encryptedKey Encrypted Key.
   * @param jsonWebKey JSON Web Key used to unwrap the Encrypted Key.
   * @param header JSON Web Encryption Header.
   * @throws {InvalidJsonWebKeyError} The provided JSON Web Key cannot be used by the JSON Web Encryption Key Management Algorithm.
   * @throws {InvalidJoseHeaderError} The provided JSON Web Encryption Header Parameters are invalid.
   * @throws {InvalidJsonWebEncryptionError} Failed to unwrap the provided Encrypted Key.
   * @returns Content Encryption Key.
   */
  public async unwrap(
    encryptedKey: Buffer,
    jsonWebKey: EllipticCurveJsonWebKey | OctetKeyPairJsonWebKey,
    header: JsonWebEncryptionHeader<ECDHESJsonWebEncryptionKeyManagementHeaderParameters>,
  ): Promise<Buffer> {
    this.validateJsonWebKey(jsonWebKey);
    await this.validateJoseHeaderParameters(header.parameters);

    const sharedSecret = await this.deriveKey(jsonWebKey, header);

    switch (this.algorithm) {
      case 'ECDH-ES':
        return sharedSecret;

      default: {
        const aesKeyWrapJsonWebKey = (await create({
          kty: 'oct',
          k: sharedSecret.toString('base64url'),
        })) as OctetSequenceJsonWebKey;

        return await this.aesKeyWrapBackend!.unwrap(encryptedKey, aesKeyWrapJsonWebKey, header);
      }
    }
  }

  /**
   * Generates a new Content Encryption Key.
   *
   * @param jsonWebKey JSON Web Key used to wrap the Content Encryption Key.
   * @param header JSON Web Encryption Header.
   * @throws {InvalidJsonWebKeyError} The provided JSON Web Key cannot be used by the JSON Web Encryption Key Management Algorithm.
   * @throws {InvalidJoseHeaderError} The provided JSON Web Encryption Header Parameters are invalid.
   * @throws {InvalidJsonWebEncryptionError} Failed to generate a Content Encryption Key.
   * @returns Generated Content Encryption Key.
   */
  public async generateContentEncryptionKey(
    jsonWebKey: EllipticCurveJsonWebKey | OctetKeyPairJsonWebKey,
    header: JsonWebEncryptionHeader<ECDHESJsonWebEncryptionKeyManagementHeaderParameters>,
  ): Promise<Buffer> {
    this.validateJsonWebKey(jsonWebKey);
    await this.validateJoseHeaderParameters(header.parameters);

    switch (this.algorithm) {
      case 'ECDH-ES':
        return await this.deriveKey(jsonWebKey, header);

      default:
        return await randomBytesAsync(header.contentEncryptionBackend.contentEncryptionKeySize);
    }
  }

  /**
   * Checks if the provided JSON Web Key can be used.
   *
   * @param jsonWebKey JSON Web Key to be checked.
   * @throws {InvalidJsonWebKeyError} The provided JSON Web Key cannot be used by the JSON Web Encryption Key Management Algorithm.
   */
  protected override validateJsonWebKey(jsonWebKey: EllipticCurveJsonWebKey | OctetKeyPairJsonWebKey): void {
    super.validateJsonWebKey(jsonWebKey);

    if (jsonWebKey.parameters.kty !== 'EC' && jsonWebKey.parameters.kty !== 'OKP') {
      throw new InvalidJsonWebKeyError('The JSON Web Encryption Algorithm only accepts "EC" and "OKP" JSON Web Keys.');
    }

    if (
      !ECDHESJsonWebEncryptionKeyManagementBackend.#curves.includes(
        jsonWebKey.parameters.crv as EllipticCurve | MontgomeryCurve,
      )
    ) {
      throw new InvalidJsonWebKeyError(
        'The JSON Web Key Parameter "crv" must be "P-256", "P-384", "P-521", "X25519", "X448" or "secp256k1".',
      );
    }
  }

  /**
   * Validates the provided JOSE Header Parameters.
   *
   * @param parameters JOSE Header Parameters.
   * @throws {InvalidJoseHeaderError} The provided JOSE Header Parameters are invalid.
   */
  private async validateJoseHeaderParameters(
    parameters: ECDHESJsonWebEncryptionKeyManagementHeaderParameters,
  ): Promise<void> {
    if (!JsonWebKey.isJsonWebKeyParameters(parameters.epk) || 'd' in parameters.epk) {
      throw new InvalidJoseHeaderError('Invalid JOSE Header Parameter "epk".');
    }

    try {
      const ephemeralKey = (await create(parameters.epk)) as EllipticCurveJsonWebKey | OctetKeyPairJsonWebKey;
      this.validateJsonWebKey(ephemeralKey);
    } catch (error: unknown) {
      throw new InvalidJoseHeaderError('Invalid JOSE Header Parameter "epk".', { cause: error });
    }

    if ('apu' in parameters && !isNonEmptyString(parameters.apu)) {
      throw new InvalidJoseHeaderError('Invalid JOSE Header Parameter "apu".');
    }

    if ('apv' in parameters && !isNonEmptyString(parameters.apv)) {
      throw new InvalidJoseHeaderError('Invalid JOSE Header Parameter "apv".');
    }

    if ('apu' in parameters && 'apv' in parameters && parameters.apu === parameters.apv) {
      throw new InvalidJoseHeaderError('The JOSE Header Parameters "apu" and "apv" cannot be equal.');
    }
  }

  /**
   * Checks if both JSON Web Keys can be used to generate a shared secret.
   *
   * @param jsonWebKey JSON Web Key of the recipient.
   * @param ephemeralKey JSON Web Key of the producer.
   * @throws {InvalidJoseHeaderError} The provided JSON Web Encryption Header Parameters are invalid.
   */
  private validateJsonWebKeys(
    jsonWebKey: EllipticCurveJsonWebKey | OctetKeyPairJsonWebKey,
    ephemeralKey: EllipticCurveJsonWebKey | OctetKeyPairJsonWebKey,
  ): void {
    if (jsonWebKey.parameters.crv !== ephemeralKey.parameters.crv) {
      throw new InvalidJoseHeaderError('Invalid JOSE Header Parameter "epk".');
    }
  }

  /**
   * Performs a Diffie-Hellman to obtain a Shared Secret and derives a Key using Concat KDF.
   *
   * @param jsonWebKey Recipient JSON Web key.
   * @param header JSON Web Encryption Header Parameters.
   * @returns Derived Key.
   */
  private async deriveKey(
    jsonWebKey: EllipticCurveJsonWebKey | OctetKeyPairJsonWebKey,
    header: JsonWebEncryptionHeader<ECDHESJsonWebEncryptionKeyManagementHeaderParameters>,
  ): Promise<Buffer> {
    const ephemeralKey = (await create(header.parameters.epk)) as EllipticCurveJsonWebKey | OctetKeyPairJsonWebKey;
    this.validateJsonWebKeys(jsonWebKey, ephemeralKey);
    const sharedSecret = diffieHellman({ privateKey: jsonWebKey.cryptoKey, publicKey: ephemeralKey.cryptoKey });

    const keyLength =
      this.algorithm === 'ECDH-ES'
        ? header.contentEncryptionBackend.contentEncryptionKeySize << 3
        : Number.parseInt(this.algorithm.substring(9, 12), 10);

    const keyLengthBuffer = Buffer.alloc(4);
    keyLengthBuffer.writeUInt32BE(keyLength);

    const partyUInfo = header.parameters.apu;
    const partyVInfo = header.parameters.apv;

    const value = Buffer.concat([
      this.lengthAndInput(Buffer.from(this.algorithm === 'ECDH-ES' ? header.parameters.enc : this.algorithm, 'ascii')),
      this.lengthAndInput(isNonEmptyString(partyUInfo) ? Buffer.from(partyUInfo, 'base64url') : Buffer.alloc(0)),
      this.lengthAndInput(isNonEmptyString(partyVInfo) ? Buffer.from(partyVInfo, 'base64url') : Buffer.alloc(0)),
      keyLengthBuffer,
      Buffer.alloc(0),
    ]);

    return this.concatKdf(sharedSecret, keyLength, value);
  }

  /**
   * Returns a Buffer containing a 32-bit long length of the provided input followed by the input itself.
   *
   * @param input Input value to be formatted.
   * @returns Resulting LV Buffer.
   */
  private lengthAndInput(input: Buffer): Buffer {
    const length = Buffer.alloc(4);
    length.writeUInt32BE(input.length);
    return Buffer.concat([length, input]);
  }

  /**
   * Returns the result of the Concat KDF.
   *
   * @param secret Diffie-Hellman Shared Secret.
   * @param keyLength Key length.
   * @param value Input value.
   */
  private concatKdf(secret: Buffer, keyLength: number, value: Buffer): Buffer {
    const iterations = Math.ceil((keyLength >> 3) / 32);
    const kdf = Buffer.alloc(iterations << 5);

    for (let iteration = 0; iteration < iterations; iteration++) {
      const input = Buffer.alloc(4 + secret.length + value.length);

      input.writeUInt32BE(iteration + 1);
      input.set(secret, 4);
      input.set(value, 4 + secret.length);

      kdf.set(createHash('sha-256').update(input).digest(), iteration << 5);
    }

    return kdf.subarray(0, keyLength >> 3);
  }
}
