import { Buffer } from 'buffer';

import { InvalidJsonWebEncryptionError } from '../../../../errors/invalid-jsonwebencryption.error';
import { InvalidJsonWebKeyError } from '../../../../errors/invalid-jsonwebkey.error';
import { JsonWebEncryptionHeader } from '../../../../jwe/jsonwebencryption-header';
import { OctetSequenceJsonWebKey } from '../../../jwk/oct/octet-sequence.jsonwebkey';
import { JsonWebEncryptionKeyManagementBackend } from '../jsonwebencryption-key-management.backend';

/**
 * Implementation of the dir JSON Web Encryption Backend.
 *
 * @see {@link https://www.rfc-editor.org/rfc/rfc7518.html#section-4.5|RFC 7518 Direct Encryption with a Shared Symmetric Key}
 */
export class DirJsonWebEncryptionKeyManagementBackend extends JsonWebEncryptionKeyManagementBackend {
  /**
   * Instantiates a new dir JSON Web Encryption Key Management Backend.
   */
  public constructor() {
    super('dir');
  }

  /**
   * Wraps the provided Content Encryption Key.
   *
   * If additional header parameters are generated by the backend,
   * it will be automatically added to the header by the method.
   *
   * @param _cek ~Content Encryption Key.~
   * @param jwk JSON Web Key used to wrap the Content Encryption Key.
   * @param _header ~JSON Web Encryption Header.~
   * @throws {InvalidJsonWebKeyError} The provided JSON Web Key cannot be used by the JSON Web Encryption Key Management Algorithm.
   * @throws {InvalidJoseHeaderError} The provided JSON Web Encryption Header Parameters are invalid.
   * @returns Encrypted Key.
   */
  public async wrap(_cek: Buffer, jwk: OctetSequenceJsonWebKey, _header: JsonWebEncryptionHeader): Promise<Buffer> {
    this.validateJsonWebKey(jwk);
    return Buffer.alloc(0);
  }

  /**
   * Unwraps the provided Encrypted Key.
   *
   * @param ek Encrypted Key.
   * @param jwk JSON Web Key used to unwrap the Encrypted Key.
   * @param _header ~JSON Web Encryption Header.~
   * @throws {InvalidJsonWebKeyError} The provided JSON Web Key cannot be used by the JSON Web Encryption Key Management Algorithm.
   * @throws {InvalidJoseHeaderError} The provided JSON Web Encryption Header Parameters are invalid.
   * @throws {InvalidJsonWebEncryptionError} Failed to unwrap the provided Encrypted Key.
   * @returns Content Encryption Key.
   */
  public async unwrap(ek: Buffer, jwk: OctetSequenceJsonWebKey, _header: JsonWebEncryptionHeader): Promise<Buffer> {
    this.validateJsonWebKey(jwk);

    if (ek.byteLength !== 0) {
      throw new InvalidJsonWebEncryptionError('The provided JSON Web Encryption is invalid.');
    }

    return Buffer.from(jwk.parameters.k, 'base64url');
  }

  /**
   * Generates a new Content Encryption Key.
   *
   * @param jwk JSON Web Key used to wrap the Content Encryption Key.
   * @param _header ~JSON Web Encryption Header.~
   * @throws {InvalidJsonWebKeyError} The provided JSON Web Key cannot be used by the JSON Web Encryption Key Management Algorithm.
   * @throws {InvalidJoseHeaderError} The provided JSON Web Encryption Header Parameters are invalid.
   * @throws {InvalidJsonWebEncryptionError} Failed to generate a Content Encryption Key.
   * @returns Generated Content Encryption Key.
   */
  public async generateContentEncryptionKey(
    jwk: OctetSequenceJsonWebKey,
    _header: JsonWebEncryptionHeader,
  ): Promise<Buffer> {
    this.validateJsonWebKey(jwk);
    return Buffer.from(jwk.parameters.k, 'base64url');
  }

  /**
   * Checks if the provided JSON Web Key can be used.
   *
   * @param jwk JSON Web Key to be checked.
   * @throws {InvalidJsonWebKeyError} The provided JSON Web Key cannot be used by the JSON Web Encryption Key Management Algorithm.
   */
  protected override validateJsonWebKey(jwk: OctetSequenceJsonWebKey): void {
    super.validateJsonWebKey(jwk);

    if (jwk.parameters.kty !== 'oct') {
      throw new InvalidJsonWebKeyError('The JSON Web Encryption Algorithm only accepts "oct" JSON Web Keys.');
    }
  }
}
