import { Buffer } from 'buffer';

import { InvalidJsonWebKeyError } from '../../../errors/invalid-jsonwebkey.error';
import { JsonWebEncryptionHeader } from '../../../jwe/jsonwebencryption-header';
import { JsonWebKey } from '../../../jwk/jsonwebkey';
import { KeyManagementAlgorithm } from './key-management-algorithm.type';

/**
 * Implementation of the JSON Web Encryption Key Management Backend.
 *
 * @see {@link https://www.rfc-editor.org/rfc/rfc7518.html#section-4|RFC 7518 Cryptographic Algorithms for Key Management}
 */
export abstract class JsonWebEncryptionKeyManagementBackend {
  /**
   * JSON Web Encryption Key Management Algorithm.
   *
   * @see {@link https://www.rfc-editor.org/rfc/rfc7516.html#section-4.1.1|RFC 7516 "alg" (Algorithm) Header Parameter}
   * @see {@link https://www.rfc-editor.org/rfc/rfc7518.html#section-4.1|RFC 7518 "alg" (Algorithm) Header Parameter Values for JWE}
   * @see {@link https://www.rfc-editor.org/rfc/rfc8037.html#section-3.2|RFC 8037 ECDH-ES}
   */
  protected readonly algorithm: KeyManagementAlgorithm;

  /**
   * Instantiates a new JSON Web Encryption Key Management Backend.
   *
   * @param algorithm JSON Web Encryption Key Management Algorithm.
   */
  public constructor(algorithm: KeyManagementAlgorithm) {
    this.algorithm = algorithm;
  }

  /**
   * Wraps the provided Content Encryption Key.
   *
   * If additional header parameters are generated by the backend,
   * it will be automatically added to the header by the method.
   *
   * @param cek Content Encryption Key.
   * @param jwk JSON Web Key used to wrap the Content Encryption Key.
   * @param header JSON Web Encryption Header.
   * @throws {InvalidJsonWebKeyError} The provided JSON Web Key cannot be used by the JSON Web Encryption Key Management Algorithm.
   * @throws {InvalidJoseHeaderError} The provided JSON Web Encryption Header Parameters are invalid.
   * @returns Encrypted Key.
   */
  public abstract wrap(cek: Buffer, jwk: JsonWebKey, header: JsonWebEncryptionHeader): Promise<Buffer>;

  /**
   * Unwraps the provided Encrypted Key.
   *
   * @param ek Encrypted Key.
   * @param jwk JSON Web Key used to unwrap the Encrypted Key.
   * @param header JSON Web Encryption Header.
   * @throws {InvalidJsonWebKeyError} The provided JSON Web Key cannot be used by the JSON Web Encryption Key Management Algorithm.
   * @throws {InvalidJoseHeaderError} The provided JSON Web Encryption Header Parameters are invalid.
   * @throws {InvalidJsonWebEncryptionError} Failed to unwrap the provided Encrypted Key.
   * @returns Content Encryption Key.
   */
  public abstract unwrap(ek: Buffer, jwk: JsonWebKey, header: JsonWebEncryptionHeader): Promise<Buffer>;

  /**
   * Generates a new Content Encryption Key.
   *
   * @param jwk JSON Web Key used to wrap the Content Encryption Key.
   * @param header JSON Web Encryption Header.
   * @throws {InvalidJsonWebKeyError} The provided JSON Web Key cannot be used by the JSON Web Encryption Key Management Algorithm.
   * @throws {InvalidJoseHeaderError} The provided JSON Web Encryption Header Parameters are invalid.
   * @throws {InvalidJsonWebEncryptionError} Failed to generate a Content Encryption Key.
   * @returns Generated Content Encryption Key.
   */
  public abstract generateContentEncryptionKey(jwk: JsonWebKey, header: JsonWebEncryptionHeader): Promise<Buffer>;

  /**
   * Checks if the provided JSON Web Key can be used.
   *
   * @param jwk JSON Web Key to be checked.
   * @throws {InvalidJsonWebKeyError} The provided JSON Web Key cannot be used by the JSON Web Encryption Key Management Algorithm.
   */
  protected validateJsonWebKey(jwk: JsonWebKey): void {
    if ('alg' in jwk.parameters && jwk.parameters.alg !== this.algorithm) {
      throw new InvalidJsonWebKeyError(
        'The provided JSON Web Key cannot be used by the JSON Web Encryption Algorithm.',
      );
    }
  }
}
