import { Buffer } from 'buffer';
import { pbkdf2, randomBytes } from 'crypto';
import { promisify } from 'util';

import { isNonEmptyString } from '@guarani/primitives';

import { InvalidJoseHeaderError } from '../../../../errors/invalid-jose-header.error';
import { InvalidJsonWebKeyError } from '../../../../errors/invalid-jsonwebkey.error';
import { JsonWebEncryptionHeader } from '../../../../jwe/jsonwebencryption-header';
import { createJsonWebKey } from '../../../../jwk/create-jsonwebkey';
import { OctetSequenceJsonWebKey } from '../../../jwk/oct/octet-sequence.jsonwebkey';
import { AESKWJsonWebEncryptionKeyManagementBackend } from '../aeskw/aeskw-jsonwebencryption-key-management.backend';
import { JsonWebEncryptionKeyManagementBackend } from '../jsonwebencryption-key-management.backend';
import { KeyManagementAlgorithm } from '../key-management-algorithm.type';
import { PBES2JsonWebEncryptionKeyManagementHeaderParameters } from './pbes2-jsonwebencryption-key-management-header.parameters';

const pbkdf2Async = promisify(pbkdf2);
const randomBytesAsync = promisify(randomBytes);

/**
 * Implementation of the PBES2 JSON Web Encryption Key Management Backend.
 *
 * @see {@link https://www.rfc-editor.org/rfc/rfc7518.html#section-4.8|RFC 7518 Key Encryption with PBES2}
 */
export class PBES2JsonWebEncryptionKeyManagementBackend extends JsonWebEncryptionKeyManagementBackend {
  /**
   * Hash Algorithm.
   */
  private readonly hash: string;

  /**
   * AES Key Wrap JSON Web Encryption Key Management Backend.
   */
  private readonly aeskwBackend: AESKWJsonWebEncryptionKeyManagementBackend;

  /**
   * Minimum size of the Salt Input in bytes.
   */
  private readonly minimumSaltSize: number = 8;

  /**
   * Minimum number of Iteration Count.
   */
  private readonly minimumIterationCount: number = 1000;

  /**
   * Instantiates a new PBES2 JSON Web Encryption Key Management Backend.
   *
   * @param algorithm JSON Web Encryption Key Management Algorithm.
   */
  public constructor(
    algorithm: Extract<KeyManagementAlgorithm, 'PBES2-HS256+A128KW' | 'PBES2-HS384+A192KW' | 'PBES2-HS512+A256KW'>,
  ) {
    super(algorithm);

    const [hashSize, keySize] = /^PBES2-HS([0-9]{3})\+A([0-9]{3})KW$/
      .exec(algorithm)!
      .slice(1)
      .map((value) => Number.parseInt(value)) as [number, number];

    this.hash = `sha-${hashSize}`;

    this.aeskwBackend = new AESKWJsonWebEncryptionKeyManagementBackend(
      `A${keySize}KW` as Extract<KeyManagementAlgorithm, 'A128KW' | 'A192KW' | 'A256KW'>,
    );
  }

  /**
   * Wraps the provided Content Encryption Key.
   *
   * If additional header parameters are generated by the backend,
   * it will be automatically added to the header by the method.
   *
   * @param cek Content Encryption Key.
   * @param jwk JSON Web Key used to wrap the Content Encryption Key.
   * @param header JSON Web Encryption Header.
   * @throws {InvalidJsonWebKeyError} The provided JSON Web Key cannot be used by the JSON Web Encryption Key Management Algorithm.
   * @throws {InvalidJoseHeaderError} The provided JSON Web Encryption Header Parameters are invalid.
   * @returns Encrypted Key.
   */
  public async wrap(
    cek: Buffer,
    jwk: OctetSequenceJsonWebKey,
    header: JsonWebEncryptionHeader<PBES2JsonWebEncryptionKeyManagementHeaderParameters>,
  ): Promise<Buffer> {
    this.validateJsonWebKey(jwk);
    this.validateJoseHeaderParameters(header.parameters);

    const derivedKey = await this.deriveKey(jwk, header);

    const aeskwJwk = (await createJsonWebKey({
      kty: 'oct',
      k: derivedKey.toString('base64url'),
    })) as OctetSequenceJsonWebKey;

    return await this.aeskwBackend.wrap(cek, aeskwJwk, header);
  }

  /**
   * Unwraps the provided Encrypted Key.
   *
   * @param ek Encrypted Key.
   * @param jwk JSON Web Key used to unwrap the Encrypted Key.
   * @param header JSON Web Encryption Header.
   * @throws {InvalidJsonWebKeyError} The provided JSON Web Key cannot be used by the JSON Web Encryption Key Management Algorithm.
   * @throws {InvalidJoseHeaderError} The provided JSON Web Encryption Header Parameters are invalid.
   * @throws {InvalidJsonWebEncryptionError} Failed to unwrap the provided Encrypted Key.
   * @returns Content Encryption Key.
   */
  public async unwrap(
    ek: Buffer,
    jwk: OctetSequenceJsonWebKey,
    header: JsonWebEncryptionHeader<PBES2JsonWebEncryptionKeyManagementHeaderParameters>,
  ): Promise<Buffer> {
    this.validateJsonWebKey(jwk);
    this.validateJoseHeaderParameters(header.parameters);

    const derivedKey = await this.deriveKey(jwk, header);

    const aeskwJwk = (await createJsonWebKey({
      kty: 'oct',
      k: derivedKey.toString('base64url'),
    })) as OctetSequenceJsonWebKey;

    return await this.aeskwBackend.unwrap(ek, aeskwJwk, header);
  }

  /**
   * Generates a new Content Encryption Key.
   *
   * @param jwk JSON Web Key used to wrap the Content Encryption Key.
   * @param header JSON Web Encryption Header.
   * @throws {InvalidJsonWebKeyError} The provided JSON Web Key cannot be used by the JSON Web Encryption Key Management Algorithm.
   * @throws {InvalidJoseHeaderError} The provided JSON Web Encryption Header Parameters are invalid.
   * @throws {InvalidJsonWebEncryptionError} Failed to generate a Content Encryption Key.
   * @returns Generated Content Encryption Key.
   */
  public async generateContentEncryptionKey(
    jwk: OctetSequenceJsonWebKey,
    header: JsonWebEncryptionHeader<PBES2JsonWebEncryptionKeyManagementHeaderParameters>,
  ): Promise<Buffer> {
    this.validateJsonWebKey(jwk);
    return await randomBytesAsync(header.contentEncryptionBackend.cekSize);
  }

  /**
   * Checks if the provided JSON Web Key can be used.
   *
   * @param jwk JSON Web Key to be checked.
   * @throws {InvalidJsonWebKeyError} The provided JSON Web Key cannot be used by the JSON Web Encryption Key Management Algorithm.
   */
  protected override validateJsonWebKey(jwk: OctetSequenceJsonWebKey): void {
    super.validateJsonWebKey(jwk);

    if (jwk.parameters.kty !== 'oct') {
      throw new InvalidJsonWebKeyError('The JSON Web Encryption Algorithm only accepts "oct" JSON Web Keys.');
    }
  }

  /**
   * Validates the provided JOSE Header Parameters.
   *
   * @param parameters JOSE Header Parameters.
   * @throws {InvalidJoseHeaderError} The provided JOSE Header Parameters are invalid.
   */
  private validateJoseHeaderParameters(parameters: PBES2JsonWebEncryptionKeyManagementHeaderParameters): void {
    if (!isNonEmptyString(parameters.p2s) || Buffer.byteLength(parameters.p2s, 'base64url') < this.minimumSaltSize) {
      throw new InvalidJoseHeaderError('Invalid JOSE Header Parameter "p2s".');
    }

    if (
      typeof parameters.p2c !== 'number' ||
      !Number.isSafeInteger(parameters.p2c) ||
      parameters.p2c < this.minimumIterationCount
    ) {
      throw new InvalidJoseHeaderError('Invalid JOSE Header Parameter "p2c".');
    }
  }

  /**
   * Performs a PBKDF2 to derive a Key.
   *
   * @param jwk Recipient JSON Web key.
   * @param header JSON Web Encryption Header Parameters.
   * @returns Derived Key.
   */
  private async deriveKey(
    jwk: OctetSequenceJsonWebKey,
    header: JsonWebEncryptionHeader<PBES2JsonWebEncryptionKeyManagementHeaderParameters>,
  ): Promise<Buffer> {
    const keySize = Number.parseInt(this.aeskwBackend['algorithm'].substring(1, 4)) >> 3;

    const salt = Buffer.concat([
      Buffer.from(this.algorithm, 'utf8'),
      Buffer.from([0x00]),
      Buffer.from(header.parameters.p2s, 'base64url'),
    ]);

    const password = Buffer.from(jwk.parameters.k, 'base64url');

    return await pbkdf2Async(password, salt, header.parameters.p2c, keySize, this.hash);
  }
}
