import { Buffer } from 'buffer';
import { constants, privateDecrypt, publicEncrypt, randomBytes } from 'crypto';
import { promisify } from 'util';

import { InvalidJsonWebEncryptionError } from '../../../../errors/invalid-jsonwebencryption.error';
import { InvalidJsonWebKeyError } from '../../../../errors/invalid-jsonwebkey.error';
import { JsonWebEncryptionHeader } from '../../../../jwe/jsonwebencryption-header';
import { RsaJsonWebKey } from '../../../jwk/rsa/rsa.jsonwebkey';
import { JsonWebEncryptionKeyManagementBackend } from '../jsonwebencryption-key-management.backend';
import { KeyManagementAlgorithm } from '../key-management-algorithm.type';

const randomBytesAsync = promisify(randomBytes);

/**
 * Implementation of the RSAES JSON Web Encryption Key Management Backend.
 *
 * @see {@link https://www.rfc-editor.org/rfc/rfc7518.html#section-4.2|RFC 7518 Key Encryption with RSAES-PKCS1-v1_5}
 * @see {@link https://www.rfc-editor.org/rfc/rfc7518.html#section-4.3|RFC 7518 Key Encryption with RSAES OAEP}
 */
export class RSAESJsonWebEncryptionKeyManagementBackend extends JsonWebEncryptionKeyManagementBackend {
  /**
   * Hash Algorithm.
   */
  private readonly hash?: string;

  /**
   * RSA Padding.
   */
  private readonly padding: number;

  /**
   * Instantiates a new RSAES Key Wrap JSON Web Encryption Key Management Backend.
   *
   * @param algorithm JSON Web Encryption Key Management Algorithm.
   */
  public constructor(
    algorithm: Extract<
      KeyManagementAlgorithm,
      'RSA-OAEP' | 'RSA-OAEP-256' | 'RSA-OAEP-384' | 'RSA-OAEP-512' | 'RSA1_5'
    >,
  ) {
    super(algorithm);

    if (algorithm !== 'RSA1_5') {
      this.hash = algorithm === 'RSA-OAEP' ? 'sha-1' : `sha-${algorithm.substring(9)}`;
    }

    this.padding = algorithm === 'RSA1_5' ? constants.RSA_PKCS1_PADDING : constants.RSA_PKCS1_OAEP_PADDING;
  }

  /**
   * Wraps the provided Content Encryption Key.
   *
   * If additional header parameters are generated by the backend,
   * it will be automatically added to the header by the method.
   *
   * @param contentEncryptionKey Content Encryption Key.
   * @param jsonWebKey JSON Web Key used to wrap the Content Encryption Key.
   * @param _header ~JSON Web Encryption Header.~
   * @throws {InvalidJsonWebKeyError} The provided JSON Web Key cannot be used by the JSON Web Encryption Key Management Algorithm.
   * @throws {InvalidJoseHeaderError} The provided JSON Web Encryption Header Parameters are invalid.
   * @returns Encrypted Key.
   */
  public async wrap(
    contentEncryptionKey: Buffer,
    jsonWebKey: RsaJsonWebKey,
    _header: JsonWebEncryptionHeader,
  ): Promise<Buffer> {
    this.validateJsonWebKey(jsonWebKey);
    return publicEncrypt(
      { key: jsonWebKey.cryptoKey, padding: this.padding, oaepHash: this.hash },
      contentEncryptionKey,
    );
  }

  /**
   * Unwraps the provided Encrypted Key.
   *
   * @param encryptedKey Encrypted Key.
   * @param jsonWebKey JSON Web Key used to unwrap the Encrypted Key.
   * @param _header ~JSON Web Encryption Header.~
   * @throws {InvalidJsonWebKeyError} The provided JSON Web Key cannot be used by the JSON Web Encryption Key Management Algorithm.
   * @throws {InvalidJoseHeaderError} The provided JSON Web Encryption Header Parameters are invalid.
   * @throws {InvalidJsonWebEncryptionError} Failed to unwrap the provided Encrypted Key.
   * @returns Content Encryption Key.
   */
  public async unwrap(
    encryptedKey: Buffer,
    jsonWebKey: RsaJsonWebKey,
    _header: JsonWebEncryptionHeader,
  ): Promise<Buffer> {
    this.validateJsonWebKey(jsonWebKey);

    if (jsonWebKey.cryptoKey.type !== 'private') {
      throw new InvalidJsonWebKeyError('The provided JSON Web Key cannot be used to unwrap an Encrypted Key.');
    }

    try {
      return privateDecrypt({ key: jsonWebKey.cryptoKey, padding: this.padding, oaepHash: this.hash }, encryptedKey);
    } catch (error: unknown) {
      throw new InvalidJsonWebEncryptionError('The provided JSON Web Encryption is invalid.', { cause: error });
    }
  }

  /**
   * Generates a new Content Encryption Key.
   *
   * @param jsonWebKey JSON Web Key used to wrap the Content Encryption Key.
   * @param header JSON Web Encryption Header.
   * @throws {InvalidJsonWebKeyError} The provided JSON Web Key cannot be used by the JSON Web Encryption Key Management Algorithm.
   * @throws {InvalidJoseHeaderError} The provided JSON Web Encryption Header Parameters are invalid.
   * @throws {InvalidJsonWebEncryptionError} Failed to generate a Content Encryption Key.
   * @returns Generated Content Encryption Key.
   */
  public async generateContentEncryptionKey(
    jsonWebKey: RsaJsonWebKey,
    header: JsonWebEncryptionHeader,
  ): Promise<Buffer> {
    this.validateJsonWebKey(jsonWebKey);
    return await randomBytesAsync(header.contentEncryptionBackend.contentEncryptionKeySize);
  }

  /**
   * Checks if the provided JSON Web Key can be used.
   *
   * @param jsonWebKey JSON Web Key to be checked.
   * @throws {InvalidJsonWebKeyError} The provided JSON Web Key cannot be used by the JSON Web Encryption Key Management Algorithm.
   */
  protected override validateJsonWebKey(jsonWebKey: RsaJsonWebKey): void {
    super.validateJsonWebKey(jsonWebKey);

    if (jsonWebKey.parameters.kty !== 'RSA') {
      throw new InvalidJsonWebKeyError('The JSON Web Encryption Algorithm only accepts "RSA" JSON Web Keys.');
    }
  }
}
