import { Buffer } from 'buffer';
import { createCipheriv, createDecipheriv, randomBytes } from 'crypto';
import { promisify } from 'util';

import { InvalidJsonWebEncryptionError } from '../../../../errors/invalid-jsonwebencryption.error';
import { InvalidJsonWebKeyError } from '../../../../errors/invalid-jsonwebkey.error';
import { JsonWebEncryptionHeader } from '../../../../jwe/jsonwebencryption-header';
import { OctetSequenceJsonWebKey } from '../../../jwk/oct/octet-sequence.jsonwebkey';
import { JsonWebEncryptionKeyManagementBackend } from '../jsonwebencryption-key-management.backend';
import { KeyManagementAlgorithm } from '../key-management-algorithm.type';

const randomBytesAsync = promisify(randomBytes);

/**
 * Implementation of the AES Key Wrap JSON Web Encryption Key Management Backend.
 *
 * @see {@link https://www.rfc-editor.org/rfc/rfc7518.html#section-4.4|RFC 7518 Key Wrapping with AES Key Wrap}
 */
export class AESKWJsonWebEncryptionKeyManagementBackend extends JsonWebEncryptionKeyManagementBackend {
  /**
   * Size of the JSON Web Key in bytes.
   */
  private readonly keySize: number;

  /**
   * Cipher Algorithm.
   */
  private readonly cipher: string;

  /**
   * Initialization Vector.
   */
  private readonly iv: Buffer = Buffer.alloc(8, 0xa6);

  /**
   * Instantiates a new AES Key Wrap JSON Web Encryption Key Management Backend.
   *
   * @param algorithm JSON Web Encryption Key Management Algorithm.
   */
  public constructor(algorithm: Extract<KeyManagementAlgorithm, 'A128KW' | 'A192KW' | 'A256KW'>) {
    super(algorithm);

    const bitSize = Number.parseInt(algorithm.substring(1, 4));

    this.keySize = bitSize >> 3;
    this.cipher = `aes${bitSize}-wrap`;
  }

  /**
   * Wraps the provided Content Encryption Key.
   *
   * If additional header parameters are generated by the backend,
   * it will be automatically added to the header by the method.
   *
   * @param cek Content Encryption Key.
   * @param jwk JSON Web Key used to wrap the Content Encryption Key.
   * @param _header ~JSON Web Encryption Header.~
   * @throws {InvalidJsonWebKeyError} The provided JSON Web Key cannot be used by the JSON Web Encryption Key Management Algorithm.
   * @throws {InvalidJoseHeaderError} The provided JSON Web Encryption Header Parameters are invalid.
   * @returns Encrypted Key.
   */
  public async wrap(cek: Buffer, jwk: OctetSequenceJsonWebKey, _header: JsonWebEncryptionHeader): Promise<Buffer> {
    this.validateJsonWebKey(jwk);

    const cipher = createCipheriv(this.cipher, jwk.cryptoKey, this.iv);

    return Buffer.concat([cipher.update(cek), cipher.final()]);
  }

  /**
   * Unwraps the provided Encrypted Key.
   *
   * @param ek Encrypted Key.
   * @param jwk JSON Web Key used to unwrap the Encrypted Key.
   * @param _header ~JSON Web Encryption Header.~
   * @throws {InvalidJsonWebKeyError} The provided JSON Web Key cannot be used by the JSON Web Encryption Key Management Algorithm.
   * @throws {InvalidJoseHeaderError} The provided JSON Web Encryption Header Parameters are invalid.
   * @throws {InvalidJsonWebEncryptionError} Failed to unwrap the provided Encrypted Key.
   * @returns Content Encryption Key.
   */
  public async unwrap(ek: Buffer, jwk: OctetSequenceJsonWebKey, _header: JsonWebEncryptionHeader): Promise<Buffer> {
    this.validateJsonWebKey(jwk);

    const decipher = createDecipheriv(this.cipher, jwk.cryptoKey, this.iv);

    try {
      return Buffer.concat([decipher.update(ek), decipher.final()]);
    } catch (error: unknown) {
      throw new InvalidJsonWebEncryptionError('The provided JSON Web Encryption is invalid.', { cause: error });
    }
  }

  /**
   * Generates a new Content Encryption Key.
   *
   * @param jwk JSON Web Key used to wrap the Content Encryption Key.
   * @param header JSON Web Encryption Header.
   * @throws {InvalidJsonWebKeyError} The provided JSON Web Key cannot be used by the JSON Web Encryption Key Management Algorithm.
   * @throws {InvalidJoseHeaderError} The provided JSON Web Encryption Header Parameters are invalid.
   * @throws {InvalidJsonWebEncryptionError} Failed to generate a Content Encryption Key.
   * @returns Generated Content Encryption Key.
   */
  public async generateContentEncryptionKey(
    jwk: OctetSequenceJsonWebKey,
    header: JsonWebEncryptionHeader,
  ): Promise<Buffer> {
    this.validateJsonWebKey(jwk);
    return await randomBytesAsync(header.contentEncryptionBackend.cekSize);
  }

  /**
   * Checks if the provided JSON Web Key can be used.
   *
   * @param jwk JSON Web Key to be checked.
   * @throws {InvalidJsonWebKeyError} The provided JSON Web Key cannot be used by the JSON Web Encryption Key Management Algorithm.
   */
  protected override validateJsonWebKey(jwk: OctetSequenceJsonWebKey): void {
    super.validateJsonWebKey(jwk);

    if (jwk.parameters.kty !== 'oct') {
      throw new InvalidJsonWebKeyError('The JSON Web Encryption Algorithm only accepts "oct" JSON Web Keys.');
    }

    if (Buffer.byteLength(jwk.parameters.k, 'base64url') !== this.keySize) {
      throw new InvalidJsonWebKeyError(`The JSON Web Key Parameter "k" must be ${this.keySize} bytes.`);
    }
  }
}
